programListSourceUrls:
  - https://raw.githubusercontent.com/kimwang1978/collect-tv-txt/refs/heads/main/bbxx_lite.m3u
#  - https://raw.githubusercontent.com/Guovin/iptv-api/gd/output/result.m3u
#  - https://raw.githubusercontent.com/yuanzl77/IPTV/main/live.m3u
#programListSourceFileLocalPath: path/to/local/files
outputFile: ./output/result.m3u8
testPingMinLatency: 2000 # 每个源地址的最低访问延迟 2000ms
testLoadMinSpeed: 800 # 每个直播源的最低读取速度 800kb/s, 低于该值的源将被过滤掉
retryTimes: 5 # 访问失败后的重试次数
#customUA: okhttp # 自定义UA
groupList:
  - group: 央视
    tvgName:
#      - CCTV1
#      - CCTV2
#      - CCTV3
#      - CCTV4
#      - CCTV5
#      - CCTV5+
#      - CCTV6
#      - CCTV8
      - CCTV9
#      - CCTV10
#      - CCTV11
#      - CCTV12
#      - CCTV13
#      - CCTV14
#      - CCTV15
#      - CCTV16
#      - CCTV17
#  - group: 卫视
#    tvgName:
#      - 北京卫视
#      - 江苏卫视
#      - 浙江卫视
#      - 湖南卫视
#      - 黑龙江卫视
#      - 辽宁卫视

# rainbowlog config file
rainbowlog:
  enable: true                    # enable logger
  level: DEBUG                    # default logger level
  label: ""                       # default logger label, if empty, will not record the label
  stack: false                    # whether print stack
  enableConsolePrinting: true     # whether print log record to console
  enableRainbowConsole: true      # whether using rainbow colors when printing to console
  timeFormat:                     # the time format of the time in each record, e.g. 'UNIX' or 'UNIXMS' or 'UNIXMICRO' or 'UNIXNANO' or '2006-01-02 15:04:05.000'
  sizeRollingFileConfig:
    enable: true                 # enable size rolling file
    logFilePath: ./log            # the path of log files
    logFileBaseName: rainbow.iptv.source.filter.log  # the base name of log file
    maxBackups: 10                # max log file backups, if it is negative, the file rotating will be disabled
    fileSizeLimit: 100M           # the max size of each log file, it is valid when MaxBackups is not negative
    encoder: txt                  # specify the log information format of the log file, 'txt' and 'json' supported.
  timeRollingFileConfig:
    enable: false                 # enable time rolling file
    logFilePath: ./log            # the path of log files
    logFileBaseName: rainbow.iptv.source.filter.log  # the base name of log file
    maxBackups: 7                 # max log file backups, if it is negative, the file rotating will be disabled
    rollingPeriod: DAY            # the rolling time period for rotating log file, e.g. 'YEAR' or 'MONTH' or 'DAY' or 'HOUR' or 'MINUTE' or 'SECOND'
    encoder: txt                  # specify the log information format of the log file, 'txt' and 'json' supported.