// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ProgramListSourceUrls          []string               `protobuf:"bytes,1,rep,name=program_list_source_urls,json=programListSourceUrls,proto3" json:"program_list_source_urls,omitempty"`
	ProgramListSourceFileLocalPath string                 `protobuf:"bytes,2,opt,name=program_list_source_file_local_path,json=programListSourceFileLocalPath,proto3" json:"program_list_source_file_local_path,omitempty"`
	OutputFile                     string                 `protobuf:"bytes,3,opt,name=output_file,json=outputFile,proto3" json:"output_file,omitempty"`
	TestPingMinLatency             int64                  `protobuf:"varint,4,opt,name=test_ping_min_latency,json=testPingMinLatency,proto3" json:"test_ping_min_latency,omitempty"`
	TestLoadMinSpeed               int64                  `protobuf:"varint,5,opt,name=test_load_min_speed,json=testLoadMinSpeed,proto3" json:"test_load_min_speed,omitempty"`
	RetryTimes                     int64                  `protobuf:"varint,6,opt,name=retry_times,json=retryTimes,proto3" json:"retry_times,omitempty"`
	GroupList                      []*GroupList           `protobuf:"bytes,7,rep,name=group_list,json=groupList,proto3" json:"group_list,omitempty"`
	CustomUA                       string                 `protobuf:"bytes,8,opt,name=custom_u_a,json=customUA,proto3" json:"custom_u_a,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetProgramListSourceUrls() []string {
	if x != nil {
		return x.ProgramListSourceUrls
	}
	return nil
}

func (x *Config) GetProgramListSourceFileLocalPath() string {
	if x != nil {
		return x.ProgramListSourceFileLocalPath
	}
	return ""
}

func (x *Config) GetOutputFile() string {
	if x != nil {
		return x.OutputFile
	}
	return ""
}

func (x *Config) GetTestPingMinLatency() int64 {
	if x != nil {
		return x.TestPingMinLatency
	}
	return 0
}

func (x *Config) GetTestLoadMinSpeed() int64 {
	if x != nil {
		return x.TestLoadMinSpeed
	}
	return 0
}

func (x *Config) GetRetryTimes() int64 {
	if x != nil {
		return x.RetryTimes
	}
	return 0
}

func (x *Config) GetGroupList() []*GroupList {
	if x != nil {
		return x.GroupList
	}
	return nil
}

func (x *Config) GetCustomUA() string {
	if x != nil {
		return x.CustomUA
	}
	return ""
}

type GroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	TvgName       []string               `protobuf:"bytes,2,rep,name=tvg_name,json=tvgName,proto3" json:"tvg_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupList) Reset() {
	*x = GroupList{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupList) ProtoMessage() {}

func (x *GroupList) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupList.ProtoReflect.Descriptor instead.
func (*GroupList) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *GroupList) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GroupList) GetTvgName() []string {
	if x != nil {
		return x.TvgName
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12\x1eRainbowIPTVSourceFilter.config\"\x9a\x03\n" +
	"\x06Config\x127\n" +
	"\x18program_list_source_urls\x18\x01 \x03(\tR\x15programListSourceUrls\x12K\n" +
	"#program_list_source_file_local_path\x18\x02 \x01(\tR\x1eprogramListSourceFileLocalPath\x12\x1f\n" +
	"\voutput_file\x18\x03 \x01(\tR\n" +
	"outputFile\x121\n" +
	"\x15test_ping_min_latency\x18\x04 \x01(\x03R\x12testPingMinLatency\x12-\n" +
	"\x13test_load_min_speed\x18\x05 \x01(\x03R\x10testLoadMinSpeed\x12\x1f\n" +
	"\vretry_times\x18\x06 \x01(\x03R\n" +
	"retryTimes\x12H\n" +
	"\n" +
	"group_list\x18\a \x03(\v2).RainbowIPTVSourceFilter.config.GroupListR\tgroupList\x12\x1c\n" +
	"\n" +
	"custom_u_a\x18\b \x01(\tR\bcustomUA\"<\n" +
	"\tGroupList\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x19\n" +
	"\btvg_name\x18\x02 \x03(\tR\atvgNameB9Z7github.com/ramboll/rainbow-iptv-source-filter/pkg/protob\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_proto_goTypes = []any{
	(*Config)(nil),    // 0: RainbowIPTVSourceFilter.config.Config
	(*GroupList)(nil), // 1: RainbowIPTVSourceFilter.config.GroupList
}
var file_config_proto_depIdxs = []int32{
	1, // 0: RainbowIPTVSourceFilter.config.Config.group_list:type_name -> RainbowIPTVSourceFilter.config.GroupList
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
